application:
  number_of_chains: 20
  chain_fork_height: 852054
  host: 'https://api.chainweb.com/chainweb/0.0/mainnet01'
  # pagination
  limit: 50
  max_height: 50
  min_height: 0
database:
  host: '127.0.0.1'
  port: 5432
  username: 'postgres'
  password: 'password'
  database_name: 'chainweb_indexer'
  require_ssl: false
